### ISSUE TITLE
[cohort] compare CDC-based ALS cohort extraction results

### ISSUE THREAD

**Issue by sxinger** [gpcnetwork/cdc_als4m_mu#4]
Compare the case agreement between HT's and SX's final ALS cohort table

**Comment by Askarafshar** [comment]
In the comparison between SX_ALS_GPC and HT_ALS_COHORTS ALS classifications, a total of 3,955 cases (**25.4%** of total cases) were consistently classified as "Confirmed" by both tables. However, there is a notable disagreement as 7,667 cases (49.2% of total cases) confirmed by SX_ALS_GPC had no corresponding ALS class assignment in HT_ALS_COHORTS. For the cases classified as "Likely," agreement is extremely rare, with only one case (less than 0.01% of total cases) receiving this classification from both tables. Additionally, there are 1,740 cases (11.2% of total cases) classified as "Likely" by SX_ALS_GPC and "Confirmed" by HT_ALS_COHORTS, suggesting some alignment but with variations in the level of certainty between the two tables. 

<img width="704" alt="Screen Shot 2024-05-07 at 10 01 51 AM" src="https://github.com/gpcnetwork/cdc_als4m_mu/assets/43677520/acf384e0-a77e-451c-9cec-7c8d78100ab6">

**Comment by turabieh** [comment]
@sxinger  @Askarafshar Comparison of CDC-based ALS cohort extraction: Hamza vs. Dr. Song implementations
[CDC Algorithm Song Vs Hamza.docx](https://github.com/gpcnetwork/cdc_als4m_mu/files/15339511/CDC.Algorithm.Song.Vs.Hamza.docx)

**Comment by sxinger** [comment]
@turabieh thank you for making the comparison! It seems the way I implemented requires stronger case-ascertainment criteria, which is ok. Please combine your three ALS case tables into a single one ALS_TABLE1 under your schema including only the confirmed and likely cases. I have also fixed the code by removing those "undetermined" cases that got mixed into my "likely" cases.  

@Askarafshar  please go ahead and use the current SX_ALS_GPC.ALS_TABLE1 (11432 confirmed, 12441 likely) as the ALS case cohort to continue your analysis. Later, we can use Hamza's cohort for sensitive analysis.
